contracts/multisig_wallet.scilla
contracts/proxy.scilla

[QSP-6] feat(proxy): add drainContractBalance from proxy contract

---

contracts/proxy.scilla
contracts/ssnlist.scilla

[QSP-2] add inline comments wrt roles in contracts

---

contracts/ssnlist.scilla

[QSP-5] feat(ssnlist): add constant number for max ssn node number

---

contracts/ssnlist.scilla

[QSP-4] fix(ssnlist): refund ssn operate which doing remove ssn operation

---

contracts/multisig_wallet.scilla
contracts/proxy.scilla
contracts/ssnlist.scilla

[QSP-1]  fix: add update staking parameter transition

---

contracts/multisig_wallet.scilla
contracts/proxy.scilla
contracts/ssnlist.scilla

[QSP-3] feat: add add_ssn2

---

contracts/ssnlist.scilla

This PR is to fix type error for ssn contract.

fix: type error

---

contracts/multisig_wallet.scilla
contracts/proxy.scilla
contracts/ssnlist.scilla

Adherence to Best Practices suggested by QSP

Adherence to Best Practices

---

README.md

Update readme for ssnlist, proxy and multisig wallet
1. addssn
2. addssn after upgrade
3. combine update min, max and contract max stake into update contract parameter
4. add drain proxy

Update readme after audit fixes

---

contracts/ssnlist.scilla
tests/transitions/stake_deposit.go

This PR is to fix the lack of subtraction while doing remove ssn.

fix: sub from totaldepositamount when remove ssn

---

contracts/ssnlist.scilla

Add check for max number of ssn operator before adding the particular ssn

fix: Add check for max number of ssn in addssn

---

contracts/multisig_wallet.scilla

Fix comments for update contract parameters

fix: errornous comment for multisig

---

contracts/ssnlist.scilla

Note: cherrypick without `urlinfo`

Refactor: reward calculation

---

contracts/ssnlist.scilla

Refactor: Rename of var

---

tests/transitions/assign_stake_reward.go
tests/transitions/remove_ssn.go
tests/transitions/stake_deposit.go

Fix some assertion due to the change of ssnlist contract.

test: fix some assertion

---

contracts/proxy.scilla
contracts/ssnlist.scilla
tests/ssnlist.scilla

This PR it to:
1. Subtract delegator's rewards from ssn operator's total rewards
2. Finish comments.

fix: sub delegator's reward from total rewards, finish comments

---

.github/workflows/workflow.yml
README.md

Right now this just typechecks the four existing contracts. And adds a badge to the README file indicating the status of the recently run action.

Scilla GitHub action to test contracts

---

contracts/proxy.scilla

Change type of cycle in `transition PopulateCommForSSN(ssn_addr: ByStr20, cycle: Uint32, comm: Uint128)` from `Uint128` to `Uint32`.

Fix proxy bugs

---

contracts/README.md

1. Removed duplicate entries in the table.
2. Change cycle type from `Uint128` to `Uint32`.

Fixed Readme for SSNListProxy

---

contracts/README.md
contracts/ssnlist.scilla

`gzil_address` -> `init_gzil_address`

update immutable var name for gzil address

---

contracts/multisig_wallet.scilla

audit 6.22

---

contracts/ssnlist.scilla
tests/ssnlist.scilla

With the PR https://github.com/Zilliqa/staking-contract/pull/129 i think we can just close this?
Fix #149 and #150

audit 6.23,6.24

---

contracts/README.md
contracts/ssnlist.scilla
tests/ssnlist.scilla

audit 6.27,6.29

---

contracts/gzil.scilla
contracts/multisig_wallet.scilla
contracts/ssnlist.scilla
tests/ssnlist.scilla

audit 6.30,6.31,6.32

---

contracts/gzil.scilla

audit 6.21

---

contracts/ssnlist.scilla
tests/ssnlist.scilla

To fix event log in `UpdateStakeReward`.

fix: event in assign rewards

---

contracts/ssnlist.scilla
tests/ssnlist.scilla

fix: issue 168 and 8.3

---

contracts/README.md
contracts/multisig_wallet.scilla
contracts/proxy.scilla
contracts/ssnlist.scilla

Fixes #174 and audit 6.4, 6.16, 7.2

fix: remove RemoveSSN. audit 6.4, 6.16, 7.2

---

contracts/ssnlist.scilla
tests/ssnlist.scilla

For audit report post 2: 6.2 6.3 6.9

fix: for audit report2
